spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgres
    password: Wang172630
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8081
  tomcat:
    connection-timeout: 1800000 # 连接超时，单位：毫秒（30 分钟）
    keep-alive-timeout: 1800000 # 保持活动超时，单位：毫秒（30 分钟）
    max-threads: 200 # 增加 Tomcat 线程池大小
  servlet:
    session:
      timeout: 30m # 会话超时，单位：分钟（30 分钟）
task:
  execution:
    pool:
      core-size: 10 # 异步任务线程池核心大小
      max-size: 50 # 异步任务线程池最大大小
      timeout: 1800000 # 异步任务执行超时，单位：毫秒（30 分钟）
    thread-name-prefix: TaskExecutor-
  scheduling:
    pool:
      size: 10
logging:
  level:
    org.springframework.web: INFO
    com.baomidou.mybatisplus: error
    org.apache.ibatis: error
    com.zaxxer.hikari: WARN

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.demo.model
  type-handlers-package: org.example.demo.config
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 启用 MyBatis 日志
    jdbc-type-for-null: VARCHAR

minio:
  endpoint: http://127.0.0.1:9005
  accessKey: why
  secretKey: Wang172630
  bucketName: 3ddata
